name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-and-checks:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: file:./dev-ci.db
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: test_ci_secret_do_not_use_in_prod
      STRIPE_SECRET_KEY: sk_test_dummy
      STRIPE_WEBHOOK_SECRET: whsec_dummy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Prisma generate / DB push / seed
        run: |
          pnpm prisma generate
          pnpm db:push
          pnpm db:seed

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm -s tsc --noEmit

      - name: Build
        run: pnpm build

